default: build

build:
	$(MAKE) -C coursework1 build
	$(MAKE) -C coursework2 build
	$(MAKE) -C worksheet0 build
	$(MAKE) -C worksheet1 build
	$(MAKE) -C worksheet2 build

clean:
	$(MAKE) -C coursework1 clean
	$(MAKE) -C coursework2 clean
	$(MAKE) -C worksheet0 clean
	$(MAKE) -C worksheet1 clean
	$(MAKE) -C worksheet2 clean

docs:
	$(MAKE) -C coursework2 docs

clean-docs:
	$(MAKE) -C coursework2 clean-docs

.PHONY: clean clean-docs